baseURL = "https://womentechspace.github.io"
languageCode = "en-us"
title = "Women Tech Space"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
summaryLength = 70


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "s"
  description = "Women Tech Space"
  facebook = ""
  twitter = "https://twitter.com/womentechspace"
  instagram = ""
  youtube = ""
  github = "https://github.com/womentechspace"
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/women-tech-space/"
  email = "belfast@djangogirls.org"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  featured_image = "/images/dg_group.jpg"
  # recent_posts_number = 2
